### ISSUE TITLE
The switch between development and production environment calendar IDs is hardcoded.

### ISSUE THREAD

**Issue by rlho** [ITPNYU/mc-reservation-tool#103] opened 2024-03-14 15:47 UTC
https://github.com/ITPNYU/mc-reservation-tool/blob/main/media_commons_booking_app/src/client/booking/components/SheetEditor.tsx#L53

https://github.com/ITPNYU/mc-reservation-tool/blob/main/media_commons_booking_app/src/client/booking/components/RoomCalendar.tsx#L24

**Comment by nopivnick** [comment] 2024-03-18 21:20
Duplicate of #96.

**Closed by nopivnick** 2024-03-18 21:20 UTC
Labels: duplicate
